import type { Metadata } from "next";
import { Audiowide, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import "@/lib/styles/reset.css";

const audiowide = Audiowide({
  display: "swap",
  subsets: ["latin"],
  weight: "400",
  variable: "--font-audiowide",
});
const noto = Noto_Sans_JP({
  display: "swap",
  preload: false,
  variable: "--font-noto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${noto.variable} ${audiowide.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
